using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FoodOrderingUtils
{
    public class OrderConfigurableItem
    {
        public int OrderConfigurableID { get; set; } //autogenerated ID
        public int OrderItemID { get; set; } //FK to order item
        public int MenuConfigurableID { get; set; } //FK to menu configurable options
        public string Title { get; set; } //configurable title
        public string Value { get; set; } //chosen value
    }
}
