using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FoodOrderingUtils
{
    public class OrderItem
    {
        public int OrderItemID { get; set; } //autogenerated id
        public int OrderID { get; set; } //foreign key to user's order 
        public int MenuItemID { get; set; } //foreign key to menu item
        public List<OrderConfigurableItem> Configurables
        {
            get;
            set;
        }

        public OrderItem()
        {
            Configurables = new List<OrderConfigurableItem>();
        }
    }
}
